/* HomeLab App-Dashboard – Seed-Registry
   Quelle: GitHub-Inventur vom 15.07.2026 – alle 11 Repos geklont und analysiert;
   Performance lokal gemessen (Headless Chromium, 15.07.2026)
   (Technologie aus package.json/Code, Umfang gezählt, Ursprung aus README/Commits,
   Screenshots aus lokal gebauten Apps).
   Alles in der App editierbar; Änderungen liegen im LocalStorage und
   können unter „Daten" als JSON exportiert werden. */

const SEED_VERSION = 15;

const URSPRUENGE = ["Claude", "Codex", "OpenAI", "Perplexity", "Lovable", "Gemini", "Sonstiges"];

// Agent-Adresse ist voreingetragen; das geheime Token trägst du lokal am Rechner ein (nie im Repo).
const SEED_PCS = [
  { id: "tamara", name: "Tamara", os: "Windows 11 (26200)", ort: "", notiz: "Laptop LAPTOP-D63BIAGK · Nutzer tamar · 6 GB RAM · 8 Kerne · Agent eingerichtet",
    agentUrl: "http://192.168.0.171:9800", agentToken: "" },
  { id: "smartaiz1", name: "smartAIZ1", os: "Windows 11 (26200)", ort: "", notiz: "PC-Name SmartAIZ1 · Nutzer andre · 16 GB RAM · 12 Kerne · Agent eingerichtet",
    agentUrl: "http://192.168.0.245:9800", agentToken: "" },
  { id: "dell-andreas", name: "Dell Andreas", os: "Windows 11 (26200)", ort: "", notiz: "PC-Name Andreas · Nutzer andre · 17 GB RAM · 20 Kerne · Haupt-Entwicklungsrechner (C:/2026/Claude)",
    agentUrl: "http://192.168.0.13:9800", agentToken: "" },
  { id: "pc4", name: "PC 4", os: "Windows", ort: "", notiz: "" },
];

const SEED_APPS = [
  {
    id: "ai-eventorganizer",
    name: "AI Messe Guide 2026",
    beschreibung: "Verwaltung von AI-Messen, -Konferenzen und -Events: Kalender, Programm, Kosten, Reise, Community, PWA (Supabase optional)",
    ursprung: ["Claude"],
    stack: ["HTML/JS statisch", "PWA", "Supabase"],
    rechner: "dell-andreas",
    lokalPfad: "C:\\2026\\Claude\\AI_Messe_Guide",
    github: "https://github.com/Andreas76761/AI_Eventorganizer",
    vercelUrl: "https://ai-messe-guide.vercel.app",
    vercelBestaetigt: true,
    lokalUrl: "http://localhost:8933",
    visibility: "public",
    letzterPush: "2026-07-14",
    umfang: { dateien: 31, loc: 4943 },
    screenshot: "screenshots/ai-eventorganizer.png",
    tags: ["produktiv", "events"],
    status: "aktiv",
    gestartet: "2026-07-06",
    technik: {
      frontend: "HTML/CSS/Vanilla JS (statisch, PWA)",
      middleware: "Service Worker (Offline-Cache); keine Server-Schicht",
      llm: "keins in der App (Seed-Daten KI-recherchiert)",
      backend: "optional Supabase (Postgres, Auth mit MFA, RLS) – sonst LocalStorage + IndexedDB",
    },
    doku: { text: "README + Benutzerhandbuch, Release-Notes und Präsentation in docs/", url: "https://github.com/Andreas76761/AI_Eventorganizer/tree/main/docs" },
    analyse: "Statisches Frontend ohne Build-Schritt, als PWA mit Service Worker; optional Supabase-Cloud (Auth mit MFA, Row-Level-Security, DSGVO-Löschung). Saubere Daten-/Logik-Trennung (data.js, karte.js, auswahl.js), aber app.js ist mit ~5.000 Zeilen ein Monolith. Beste Doku aller Apps.",
    performance: { ladezeitMs: 93, groesseKB: 1064, hinweis: "sehr schnell; komplett ohne CDN-Abhängigkeiten" },
    vorschlaege: [
      "app.js in Module aufteilen (Ansichten, Zustand, Helfer) – erleichtert Wartung deutlich",
      "Icon-/Design-System als wiederverwendbares Paket für die anderen Apps auskoppeln",
      "Playwright-Tests für die Kernflüsse (Event anlegen, Kosten, Export)",
    ],
    bewertung: { nutzen: 0, reifegrad: 4, wartbarkeit: 3, techQualitaet: 4, zukunft: 4,
      notiz: "Vorschlag aus Code-Analyse: sehr funktionsreich und produktiv auf Vercel; app.js als ~5.000-Zeilen-Monolith drückt die Wartbarkeit." },
  },
  {
    id: "diagramm-builder",
    name: "Diagramm Builder",
    beschreibung: "Diagramm-Ersteller mit Dashboard, Sankey, Use Cases und ROI-Berechnung; Import aus CSV/Excel, Export nach Excel/PDF/PowerPoint, 6 Farbschemata",
    ursprung: ["Claude"],
    stack: ["React", "Vite", "Recharts", "xlsx", "jsPDF", "pptxgenjs"],
    rechner: "",
    github: "https://github.com/Andreas76761/Diagramm_Builder",
    vercelUrl: "https://diagramm-builder.vercel.app",
    lokalUrl: "",
    visibility: "private",
    letzterPush: "2026-07-10",
    umfang: { dateien: 61, loc: 7923 },
    screenshot: "screenshots/diagramm-builder.png",
    tags: ["diagramme", "vercel.json vorhanden"],
    status: "aktiv",
    gestartet: "2026-05-03",
    technik: {
      frontend: "React + Vite, Recharts",
      middleware: "keine – Export-Bibliotheken laden per dynamischem Import",
      llm: "keins",
      backend: "keins – rein clientseitig",
    },
    doku: { text: "nur Standard-Vite-README – eigene Beschreibung fehlt", url: "https://github.com/Andreas76761/Diagramm_Builder#readme" },
    analyse: "Moderner React/Vite-Stack mit Recharts, sauber in Komponenten gegliedert. Die Export-Bibliotheken (xlsx, jsPDF, pptxgenjs) sind bereits vorbildlich per dynamischem Import in eigene Chunks getrennt – der Start lädt nur ~820 KB, der Rest kommt erst beim Export.",
    performance: { ladezeitMs: 138, groesseKB: 2476, hinweis: "schnell; Export-Chunks laden erst bei Bedarf" },
    vorschlaege: [
      "✅ umgesetzt (Branch claude/verbesserungen): README mit echter Projektbeschreibung statt Vite-Vorlage",
      "Vercel-Projekt verbinden (vercel.json liegt bereits im Repo)",
    ],
    bewertung: { nutzen: 0, reifegrad: 3, wartbarkeit: 4, techQualitaet: 4, zukunft: 4,
      notiz: "Vorschlag aus Code-Analyse: moderner React/Vite-Stack, saubere Komponenten; README noch Vite-Standard." },
  },
  {
    id: "servicevertrag-dashboard",
    name: "ServiceVertrag-Dashboard",
    beschreibung: "Automotive Service Contract Management (v7.5): KPIs, Vertragsvergleich, Garantiepakete, LCC- & ROI-Kalkulator, Aftermarket (Werkstattnetz, Retention, Penetration)",
    ursprung: ["Perplexity"],
    stack: ["HTML/JS statisch", "Chart.js (CDN)"],
    rechner: "",
    github: "https://github.com/Andreas76761/ServiceVertrag-Dashboard",
    vercelUrl: "https://servicevertrag-dashboard.vercel.app",
    lokalUrl: "",
    visibility: "private",
    letzterPush: "2026-07-08",
    umfang: { dateien: 27, loc: 17369 },
    screenshot: "screenshots/servicevertrag-dashboard.png",
    tags: ["automotive", "größte App"],
    status: "aktiv",
    gestartet: "2026-07-08",
    technik: {
      frontend: "Vanilla JS + Chart.js (seit Fix lokal in vendor/)",
      middleware: "keine",
      llm: "keins",
      backend: "keins – Daten als JS-Dateien im Repo",
    },
    doku: { text: "keine README – aber 7 aussagekräftige Screenshots im Repo", url: "https://github.com/Andreas76761/ServiceVertrag-Dashboard" },
    analyse: "Mit Perplexity gebaut (die Seite erlaubt *.preview.i.perplexity.ai). Inhaltlich die umfangreichste App: 17.369 Zeilen Vanilla-JS in 27 thematisch getrennten Dateien (KPIs, LCC, Aftermarket, Marketing …), aber ohne Modulsystem – alles global. Chart.js, jsPDF, pptxgenjs und xlsx kommen zur Laufzeit vom CDN.",
    performance: { ladezeitMs: 430, groesseKB: 2896, hinweis: "vorher 13 s (CDN-blockiert) – nach dem Fix 0,4 s und komplett offlinefähig" },
    vorschlaege: [
      "✅ umgesetzt (Branch claude/verbesserungen): Bibliotheken + Fonts lokal in vendor/ – Ladezeit 13 s → 0,4 s, offlinefähig, DSGVO-freundlich",
      "✅ umgesetzt (Branch claude/verbesserungen): README mit Bereichen, Screenshots und Startanleitung",
      "JS-Dateien in ES-Module umstellen, globale Variablen kapseln",
      "Klären, wo die App laufen soll (Vercel-Deployment fehlt bisher)",
    ],
    bewertung: { nutzen: 0, reifegrad: 4, wartbarkeit: 2, techQualitaet: 3, zukunft: 3,
      notiz: "Vorschlag aus Code-Analyse: inhaltlich sehr umfangreich (v7.5, 17.000+ Zeilen), aber Vanilla-JS ohne Build/Modulsystem und Chart.js vom CDN – Wartung wird mit der Größe schwer." },
  },
  {
    id: "thumbnail-generator",
    name: "Presentation Designer (Thumnail_Generator)",
    beschreibung: "Intelligentes PowerPoint-Archiv: Upload & KI-Analyse, Volltextsuche, Design-Varianten je Folie, Voice-Chat (Claude/GPT-4/Gemini/Llama), OCR, Notion-Sync",
    ursprung: [],
    stack: ["React", "Vite", "Tailwind", "tesseract.js", "Web Worker"],
    rechner: "dell-andreas",
    github: "https://github.com/Andreas76761/Thumnail_Generator",
    vercelUrl: "https://thumnail-generator.vercel.app",
    lokalUrl: "",
    lokalPfad: "C:\\2026\\Claude\\Thumbnail",
    visibility: "public",
    letzterPush: "2026-05-01",
    umfang: { dateien: 55, loc: 6472 },
    screenshot: "screenshots/thumbnail-generator.png",
    tags: ["präsentationen", "multi-llm", "vercel.json vorhanden"],
    status: "aktiv",
    gestartet: "2026-04-30",
    technik: {
      frontend: "React + Vite + Tailwind",
      middleware: "Web Worker (PPTX-Parsing), axios",
      llm: "wählbar: Claude 3.5 Sonnet, GPT-4 Turbo, Gemini Pro, Llama",
      backend: "Notion-API als Cloud-Sync – sonst LocalStorage",
    },
    doku: { text: "ausführliche README mit Features, Architektur und Roadmap", url: "https://github.com/Andreas76761/Thumnail_Generator#readme" },
    analyse: "Technisch die ausgereifteste React-App: Web Worker für PPTX-Parsing, virtuelles Scrollen, OCR (tesseract.js), Voice-Chat mit 4 LLM-Anbietern, Notion-Sync. Mit 436 KB das kleinste Build. Stolperstein: Vite-base ist fest auf /Thumnail_Generator/ (GitHub Pages) gestellt.",
    performance: { ladezeitMs: 75, groesseKB: 436, hinweis: "schnellste App im Test" },
    vorschlaege: [
      "✅ umgesetzt (Branch claude/verbesserungen): relativer Basispfad './' – läuft jetzt auf Vercel und überall; für GitHub Pages: VITE_BASE=/Thumnail_Generator/",
      "Umgang mit den LLM-API-Schlüsseln in der README dokumentieren",
      "Repo-Tippfehler 'Thumnail' → 'Thumbnail' bei Gelegenheit beheben",
    ],
    bewertung: { nutzen: 0, reifegrad: 3, wartbarkeit: 3, techQualitaet: 4, zukunft: 4,
      notiz: "Vorschlag aus Code-Analyse: technisch ambitioniert (Web Worker, OCR, virtuelles Scrollen, Multi-LLM); Achtung: Build nutzt GitHub-Pages-Basispfad /Thumnail_Generator/ – ergibt auf Vercel eine weiße Seite." },
  },
  {
    id: "task-hub",
    name: "Task-Hub 2026 V1",
    beschreibung: "Workspace-App aus Google AI Studio: Dashboard, Aktivitäten-Monitor, Dokumentenarchiv, Datei-Upload, Exportbereich, Admin-Bereich",
    ursprung: ["Gemini"],
    stack: ["Angular", "Angular Material", "Firebase", "@google/genai", "D3"],
    rechner: "",
    github: "https://github.com/Andreas76761/Task-Hub-2026-V1",
    vercelUrl: "",
    lokalUrl: "",
    visibility: "public",
    letzterPush: "2026-03-30",
    umfang: { dateien: 59, loc: 10953 },
    screenshot: "screenshots/task-hub.png",
    tags: ["organisation", "ai-studio"],
    status: "aktiv",
    gestartet: "2026-03-30",
    technik: {
      frontend: "Angular + Angular Material + Tailwind",
      middleware: "Express (Angular SSR)",
      llm: "Gemini (gemini-3-flash-preview)",
      backend: "Firebase / Firestore",
    },
    doku: { text: "AI-Studio-Standard-README + metadata.json; Firestore-Regeln liegen bei", url: "https://github.com/Andreas76761/Task-Hub-2026-V1#readme" },
    analyse: "Größte Codebasis (10.953 Zeilen): Angular mit Material und SSR-Konfiguration, Firebase/Firestore, @google/genai, D3. Sauber strukturiert, braucht aber GEMINI_API_KEY und Firebase-Projekt, um voll zu laufen. Lädt Inter + Material Icons von fonts.googleapis.com.",
    performance: { ladezeitMs: 430, groesseKB: 3204, hinweis: "vorher 13 s (Google-CDN blockiert) – nach dem Fix 0,4 s und offlinefähig" },
    vorschlaege: [
      "✅ umgesetzt (Branch claude/verbesserungen): Inter + Material Icons lokal gebündelt (@fontsource/inter, material-icons) – Ladezeit 13 s → 0,4 s",
      "✅ geprüft: Key-Hygiene bereits vorbildlich (.env* gitignored, nur .env.example eingecheckt, kein Key im Repo)",
      "firestore.rules mit dem Firebase-Emulator testen",
    ],
    bewertung: { nutzen: 0, reifegrad: 3, wartbarkeit: 3, techQualitaet: 4, zukunft: 4,
      notiz: "Vorschlag aus Code-Analyse: strukturierter Angular-Stack mit Material und Firebase; Firebase-Konfiguration und Gemini-Key nötig, um alles zu nutzen." },
  },
  {
    id: "ki-hub",
    name: "KI-Hub 2026",
    beschreibung: "KI-Portal aus Google AI Studio: Dashboard mit KI-Generierungen, KI-Tools, Dokumente, Aktivitäten, Präsentationen, Administration (benötigt GEMINI_API_KEY)",
    ursprung: ["Gemini"],
    stack: ["React", "Vite", "TypeScript", "@google/genai", "Recharts"],
    rechner: "",
    github: "https://github.com/Andreas76761/KI-Hub-2026",
    vercelUrl: "",
    lokalUrl: "",
    visibility: "private",
    letzterPush: "2026-03-30",
    umfang: { dateien: 24, loc: 1431 },
    screenshot: "screenshots/ki-hub.png",
    tags: ["ki", "ai-studio"],
    status: "aktiv",
    gestartet: "2026-03-30",
    technik: {
      frontend: "React + Vite + TypeScript",
      middleware: "keine",
      llm: "Gemini (gemini-3-flash-preview)",
      backend: "keins – Demo-Daten im Frontend",
    },
    doku: { text: "AI-Studio-README + requirements.md mit Anforderungen", url: "https://github.com/Andreas76761/KI-Hub-2026#readme" },
    analyse: "Kompaktes, aufgeräumtes React/TypeScript-Projekt (1.431 Zeilen) mit Recharts und @google/genai. Kritisch: new GoogleGenAI() läuft beim Modul-Import – ohne GEMINI_API_KEY stürzt die ganze App mit weißer Seite ab (process.env existiert im Browser nicht).",
    performance: { ladezeitMs: 137, groesseKB: 1160, hinweis: "schnell; startet seit dem Fix auch ohne Key" },
    vorschlaege: [
      "✅ umgesetzt (Branch claude/verbesserungen): App startet ohne Key und zeigt einen Hinweis im Chat statt weißer Seite; Key kommt sauber aus .env.local",
      "✅ umgesetzt (Branch claude/verbesserungen): test.txt aus dem Repo entfernt",
    ],
    bewertung: { nutzen: 0, reifegrad: 2, wartbarkeit: 3, techQualitaet: 3, zukunft: 3,
      notiz: "Vorschlag aus Code-Analyse: aufgeräumtes React/TypeScript, aber die App stürzt ohne GEMINI_API_KEY komplett ab (weiße Seite) – Key-Handling sollte abgefangen werden." },
  },
  {
    id: "baudokumentation2026",
    name: "Baudokumentation 2026 V1",
    beschreibung: "Baudokumentation, laut README „mit Claude Fable“ (11.07.2026). Auf GitHub liegt bisher nur die README – der Code ist vermutlich lokal.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/baudokumentation2026_V1",
    vercelUrl: "",
    lokalUrl: "",
    visibility: "public",
    letzterPush: "2026-07-11",
    umfang: { dateien: 1, loc: 0 },
    screenshot: "",
    tags: ["bau", "nur-readme"],
    status: "aktiv",
    gestartet: "2026-07-11",
    technik: { frontend: "unbekannt – Code liegt nicht auf GitHub", middleware: "unbekannt", llm: "unbekannt", backend: "unbekannt" },
    doku: { text: "nur README (eine Zeile)", url: "https://github.com/Andreas76761/baudokumentation2026_V1#readme" },
    analyse: "Auf GitHub liegt nur die README („Baudokumentation mit Claude Fable, 11.07.2026“) – der Code ist vermutlich lokal auf einem PC.",
    performance: null,
    vorschlaege: ["Code pushen – dann können Analyse, Screenshot und Performance-Messung nachgezogen werden", "Lokalen Pfad/PC im Dashboard eintragen (✎)"],
  },
  {
    id: "bauplaner",
    name: "Bauplaner Version 1",
    beschreibung: "„Mockup Bauplaner mit Codex“ (README). Auf GitHub liegt bisher nur die README – der Code ist vermutlich lokal.",
    ursprung: ["Codex"],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/Bauplaner_Version1",
    vercelUrl: "",
    lokalUrl: "",
    visibility: "private",
    letzterPush: "2026-06-09",
    umfang: { dateien: 1, loc: 0 },
    screenshot: "",
    tags: ["bau", "nur-readme"],
    status: "aktiv",
    gestartet: "2026-06-09",
    technik: { frontend: "unbekannt – Code liegt nicht auf GitHub", middleware: "unbekannt", llm: "unbekannt", backend: "unbekannt" },
    doku: { text: "nur README (eine Zeile)", url: "https://github.com/Andreas76761/Bauplaner_Version1#readme" },
    analyse: "Auf GitHub liegt nur die README („Mockup Bauplaner mit Codex“) – der Code ist vermutlich lokal auf einem PC.",
    performance: null,
    vorschlaege: ["Code pushen – dann können Analyse, Screenshot und Performance-Messung nachgezogen werden", "Lokalen Pfad/PC im Dashboard eintragen (✎)"],
  },
  {
    id: "taxflow",
    name: "TaxFlow",
    beschreibung: "„Built with AI Studio“ (Gemini). Auf GitHub liegt bisher nur die README – App vermutlich in AI Studio bzw. lokal.",
    ursprung: ["Gemini"],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/TaxFlow",
    vercelUrl: "",
    lokalUrl: "",
    visibility: "private",
    letzterPush: "2026-04-02",
    umfang: { dateien: 1, loc: 0 },
    screenshot: "",
    tags: ["finanzen", "ai-studio", "nur-readme"],
    status: "aktiv",
    gestartet: "2026-04-02",
    technik: { frontend: "unbekannt – Code liegt nicht auf GitHub", middleware: "unbekannt", llm: "vermutlich Gemini (AI Studio)", backend: "unbekannt" },
    doku: { text: "nur AI-Studio-Standard-README", url: "https://github.com/Andreas76761/TaxFlow#readme" },
    analyse: "„Built with AI Studio“ – die App lebt vermutlich in Google AI Studio bzw. lokal; im Repo ist noch kein Code.",
    performance: null,
    vorschlaege: ["App aus AI Studio exportieren und pushen", "Kurz beschreiben, was TaxFlow tut (README)"],
  },
  {
    id: "simulation-sc",
    name: "Simulation SC V1",
    beschreibung: "„Built with AI Studio“ (Gemini). Auf GitHub liegt bisher nur die README – App vermutlich in AI Studio bzw. lokal.",
    ursprung: ["Gemini"],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/Simulation_SC_V1",
    vercelUrl: "",
    lokalUrl: "",
    visibility: "public",
    letzterPush: "2026-03-01",
    umfang: { dateien: 1, loc: 0 },
    screenshot: "",
    tags: ["simulation", "ai-studio", "nur-readme"],
    status: "aktiv",
    gestartet: "2026-03-01",
    technik: { frontend: "unbekannt – Code liegt nicht auf GitHub", middleware: "unbekannt", llm: "vermutlich Gemini (AI Studio)", backend: "unbekannt" },
    doku: { text: "nur AI-Studio-Standard-README", url: "https://github.com/Andreas76761/Simulation_SC_V1#readme" },
    analyse: "„Built with AI Studio“ – die App lebt vermutlich in Google AI Studio bzw. lokal; im Repo ist noch kein Code.",
    performance: null,
    vorschlaege: ["App aus AI Studio exportieren und pushen", "Kurz beschreiben, was simuliert wird (README)"],
  },
  {
    id: "paperclip-bau",
    name: "Paperclip Bau",
    beschreibung: "GitHub-Repo ist leer (keine Commits) – App existiert vermutlich nur lokal oder ist noch nicht hochgeladen.",
    ursprung: [],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/Paperclip_Bau",
    vercelUrl: "",
    lokalUrl: "",
    visibility: "public",
    letzterPush: "2026-06-07",
    umfang: { dateien: 0, loc: 0 },
    screenshot: "",
    tags: ["bau", "repo-leer"],
    status: "pausiert",
    gestartet: "2026-06-07",
    technik: { frontend: "unbekannt – Repo ist leer", middleware: "unbekannt", llm: "unbekannt", backend: "unbekannt" },
    doku: { text: "keine – das Repo ist leer (0 Commits)", url: "https://github.com/Andreas76761/Paperclip_Bau" },
    analyse: "Das Repo enthält keine Commits – vermutlich ist ein früherer Upload fehlgeschlagen oder die App existiert nur lokal.",
    performance: null,
    vorschlaege: ["Lokalen Stand pushen oder das leere Repo löschen", "Falls die App lokal läuft: Pfad/PC im Dashboard eintragen"],
  },
  {
    id: "codex-blutdruck",
    name: "Blutdruckmessung (Codex)",
    beschreibung: "Lokale App zur Blutdruck-Erfassung, gebaut mit Codex. Liegt auf Tamara, noch nicht auf GitHub.",
    ursprung: ["Codex"],
    stack: [],
    rechner: "tamara",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\tamar\\Documents\\Codex-Blutdruckmessung-Andreas",
    visibility: "",
    letzterPush: "",
    tags: ["gesundheit", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Liegt lokal auf Tamara, nicht auf GitHub. Sobald der Code gepusht ist, ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: [
      "Code zu GitHub hochladen (Anleitung docs/CODE_HOCHLADEN.md) – danach volle Analyse und Screenshot",
      "Zum Starten/Stoppen aus dem Dashboard: Startkommando in agent/apps.json auf Tamara eintragen",
    ],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "testing-agent",
    name: "Testing Agent",
    beschreibung: "Lokales Projekt auf Tamara. Zweck noch offen. Noch nicht auf GitHub.",
    ursprung: [],
    stack: [],
    rechner: "tamara",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\tamar\\Documents\\Testing Agent",
    visibility: "",
    letzterPush: "",
    tags: ["nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Liegt lokal auf Tamara, nicht auf GitHub. Werkzeug/Zweck bitte per Stift ergaenzen; nach dem Push ziehe ich die Analyse nach.",
    performance: null,
    vorschlaege: [
      "Werkzeug (Claude/Codex/…) und kurze Beschreibung per Stift ergaenzen",
      "Code zu GitHub hochladen – danach volle Analyse",
    ],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "deckungsbeitrag",
    name: "Deckungsbeitragflussrechnung",
    beschreibung: "Lokale App (mit Claude/Fable gebaut): Deckungsbeitrags-/Flussrechnung mit Undo, CSV-Import, Simulations-Übernahme und Diagrammen. Noch nicht auf GitHub.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "dell-andreas",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\2026\\Claude\\Fable\\Deckungsbeitragflussrechnung",
    visibility: "",
    letzterPush: "2026-07-11",
    tags: ["finanzen", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Liegt lokal auf Dell Andreas (C:/2026/Claude/Fable/Deckungsbeitragflussrechnung), nicht auf GitHub. Letzter lokaler Commit 11.07.2026 (Undo, CSV-Import, Sim-Übernahme, Diagramme). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: [
      "Code zu GitHub hochladen (Anleitung docs/CODE_HOCHLADEN.md) – danach volle Analyse und Screenshot",
      "Zum Starten/Stoppen aus dem Dashboard: Startkommando in agent/apps.json auf Dell Andreas eintragen",
    ],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "bauplaner-ki-v2",
    name: "Bauplaner KI Version2",
    beschreibung: "Lokale App auf smartAIZ1 (Folgeversion des Bauplaner). Noch nicht auf GitHub. Werkzeug vermutlich Codex wie Version 1 – per KI-Projekt-Suche bestätigbar.",
    ursprung: [],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\andre\\Documents\\Auswertung CFD Trades\\Bauplaner_KI Version2",
    visibility: "",
    letzterPush: "2026-06-09",
    tags: ["bau", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Liegt lokal auf smartAIZ1 (C:/Users/andre/Documents/Auswertung CFD Trades/Bauplaner_KI Version2). Erst-Commit 09.06.2026. Werkzeug bitte per KI-Projekt-Suche/Stift bestätigen; nach dem Push ziehe ich die Analyse nach.",
    performance: null,
    vorschlaege: [
      "Werkzeug per KI-Projekte-Suche bestimmen (Claude/Codex/…)",
      "Code zu GitHub hochladen (Anleitung docs/CODE_HOCHLADEN.md) – danach volle Analyse",
    ],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "2026-06-09",
  },
  {
    id: "homelab-uebersicht",
    name: "HomeLab-Übersicht (Arbeitsstand)",
    beschreibung: "Vermutlich der lokale Arbeitsstand dieses HomeLab-App-Dashboards (README nennt alle Werkzeuge).",
    ursprung: ["Claude"],
    stack: [],
    rechner: "dell-andreas",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\2026\\Claude\\Übersicht",
    visibility: "",
    letzterPush: "",
    tags: ["dashboard", "meta", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf Dell Andreas (C:\\2026\\Claude\\Übersicht), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "dateiorganizer",
    name: "Dateiorganizer",
    beschreibung: "Lokale App zum Organisieren/Sortieren von Dateien.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "dell-andreas",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\2026\\Claude\\Dateiorganizer",
    visibility: "",
    letzterPush: "",
    tags: ["tools", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf Dell Andreas (C:\\2026\\Claude\\Dateiorganizer), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "releaseletter",
    name: "Releaseletter",
    beschreibung: "Lokale App für Release-/Newsletter-Texte.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "dell-andreas",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\2026\\Claude\\Releaseletter",
    visibility: "",
    letzterPush: "",
    tags: ["content", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf Dell Andreas (C:\\2026\\Claude\\Releaseletter), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "wad-2026",
    name: "WAD 2026",
    beschreibung: "Lokales Projekt (vermutlich WeAreDevelopers 2026).",
    ursprung: ["Claude"],
    stack: [],
    rechner: "dell-andreas",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\2026\\Claude\\WAD_2026",
    visibility: "",
    letzterPush: "",
    tags: ["events", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf Dell Andreas (C:\\2026\\Claude\\WAD_2026), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "design-varianten",
    name: "Design-Varianten (Messe)",
    beschreibung: "Design-Varianten-Artefakt zum Messe-Projekt.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "dell-andreas",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\2026\\Claude\\Artefact_Messe\\design-varianten",
    visibility: "",
    letzterPush: "",
    tags: ["design", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf Dell Andreas (C:\\2026\\Claude\\Artefact_Messe\\design-varianten), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "database-intelligence-hub",
    name: "Database Intelligence Hub",
    beschreibung: "Codex-Projekt aus 'AI Business Berater'.",
    ursprung: ["Codex"],
    stack: [],
    rechner: "dell-andreas",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\2026\\Codex\\AI Business Berater\\database-intelligence-hub",
    visibility: "",
    letzterPush: "",
    tags: ["daten", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf Dell Andreas (C:\\2026\\Codex\\AI Business Berater\\database-intelligence-hub), nicht auf GitHub. Werkzeug Codex (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "flatex",
    name: "Flatex (CFD-Analyse)",
    beschreibung: "Codex-Projekt zur CFD-/Trading-Analyse (Flatex).",
    ursprung: ["Codex"],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Andreas_2026\\Codex\\CFD Analyse\\Flatex",
    visibility: "",
    letzterPush: "",
    tags: ["trading", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf smartAIZ1 (C:\\Andreas_2026\\Codex\\CFD Analyse\\Flatex), nicht auf GitHub. Werkzeug Codex (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "smartaiz-ki-chat",
    name: "smartAIZ KI-Chat",
    beschreibung: "KI-Chat-App (nutzt OpenAI-API). Auch unter CLAUDE_Fable\\Artifacts vorhanden.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-ki-chat",
    visibility: "",
    letzterPush: "",
    tags: ["chat", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf smartAIZ1 (C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-ki-chat), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "baudok-bauprojekte",
    name: "Baudok Bauprojekte",
    beschreibung: "Claude-Artefakt: Bauprojekte-Verwaltung.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\andre\\Claude\\Artifacts\\baudok-bauprojekte",
    visibility: "",
    letzterPush: "",
    tags: ["bau", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf smartAIZ1 (C:\\Users\\andre\\Claude\\Artifacts\\baudok-bauprojekte), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "smartaiz-buchungssystem",
    name: "smartAIZ Buchungssystem",
    beschreibung: "Claude-Artefakt: Buchungssystem.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-buchungssystem",
    visibility: "",
    letzterPush: "",
    tags: ["buchhaltung", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf smartAIZ1 (C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-buchungssystem), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "smartaiz-cockpit",
    name: "smartAIZ Cockpit",
    beschreibung: "Claude-Artefakt: Cockpit/Übersicht.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-cockpit",
    visibility: "",
    letzterPush: "",
    tags: ["dashboard", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf smartAIZ1 (C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-cockpit), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "smartaiz-crm-app",
    name: "smartAIZ CRM-App",
    beschreibung: "Claude-Artefakt: CRM-Anwendung.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-crm-app",
    visibility: "",
    letzterPush: "",
    tags: ["crm", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf smartAIZ1 (C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-crm-app), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "smartaiz-crm-dashboard",
    name: "smartAIZ CRM-Dashboard",
    beschreibung: "Claude-Artefakt: CRM-Dashboard.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-crm-dashboard",
    visibility: "",
    letzterPush: "",
    tags: ["crm", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf smartAIZ1 (C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-crm-dashboard), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "smartaiz-intranet",
    name: "smartAIZ Intranet",
    beschreibung: "Claude-Artefakt: Intranet.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-intranet",
    visibility: "",
    letzterPush: "",
    tags: ["intranet", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf smartAIZ1 (C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-intranet), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "smartaiz-kundenportal",
    name: "smartAIZ Kundenportal",
    beschreibung: "Claude-Artefakt: Kundenportal.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-kundenportal",
    visibility: "",
    letzterPush: "",
    tags: ["portal", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf smartAIZ1 (C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-kundenportal), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "smartaiz-lms",
    name: "smartAIZ LMS",
    beschreibung: "Claude-Artefakt: Lern-Management-System.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-lms",
    visibility: "",
    letzterPush: "",
    tags: ["lernen", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf smartAIZ1 (C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-lms), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "smartaiz-management-dashboard",
    name: "smartAIZ Management-Dashboard",
    beschreibung: "Claude-Artefakt: Management-Dashboard.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-management-dashboard",
    visibility: "",
    letzterPush: "",
    tags: ["dashboard", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf smartAIZ1 (C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-management-dashboard), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "smartaiz-mindmap",
    name: "smartAIZ Mindmap",
    beschreibung: "Claude-Artefakt: Mindmap-Tool.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-mindmap",
    visibility: "",
    letzterPush: "",
    tags: ["tools", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf smartAIZ1 (C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-mindmap), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "smartaiz-wiki",
    name: "smartAIZ Wiki",
    beschreibung: "Claude-Artefakt: Wiki.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-wiki",
    visibility: "",
    letzterPush: "",
    tags: ["wissen", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf smartAIZ1 (C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-wiki), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "smartaiz-wochenplanung",
    name: "smartAIZ Wochenplanung",
    beschreibung: "Claude-Artefakt: Wochenplanung.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-wochenplanung",
    visibility: "",
    letzterPush: "",
    tags: ["planung", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf smartAIZ1 (C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-wochenplanung), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "smartaiz-zertifizierung",
    name: "smartAIZ Zertifizierung",
    beschreibung: "Claude-Artefakt: Zertifizierung.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-zertifizierung",
    visibility: "",
    letzterPush: "",
    tags: ["qm", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf smartAIZ1 (C:\\Users\\andre\\Claude\\Artifacts\\smartaiz-zertifizierung), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "steuerzentrale",
    name: "Steuerzentrale",
    beschreibung: "Claude-Artefakt: Steuer-/Verwaltungszentrale.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\andre\\Claude\\Artifacts\\steuerzentrale",
    visibility: "",
    letzterPush: "",
    tags: ["steuern", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf smartAIZ1 (C:\\Users\\andre\\Claude\\Artifacts\\steuerzentrale), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "smartaiz-agency",
    name: "smartAIZ Agency",
    beschreibung: "Claude-Projekt: smartAIZ Agency.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "smartaiz1",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Andreas_2026\\CLAUDE_Fable\\smartaiz_Agency",
    visibility: "",
    letzterPush: "",
    tags: ["business", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf smartAIZ1 (C:\\Andreas_2026\\CLAUDE_Fable\\smartaiz_Agency), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "kap-steuerbot",
    name: "KAP Steuerbot",
    beschreibung: "Codex-App: Steuer-Bot (KAP).",
    ursprung: ["Codex"],
    stack: [],
    rechner: "tamara",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\tamar\\Documents\\New project\\kap-steuerbot-app",
    visibility: "",
    letzterPush: "",
    tags: ["steuern", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf Tamara (C:\\Users\\tamar\\Documents\\New project\\kap-steuerbot-app), nicht auf GitHub. Werkzeug Codex (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "codex-kap-draft",
    name: "Codex KAP Draft",
    beschreibung: "Codex-Entwurf (KAP).",
    ursprung: ["Codex"],
    stack: [],
    rechner: "tamara",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Codex_KAP_Draft",
    visibility: "",
    letzterPush: "",
    tags: ["steuern", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf Tamara (C:\\Codex_KAP_Draft), nicht auf GitHub. Werkzeug Codex (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "baudok-dokumentensystem",
    name: "Baudok Dokumentensystem",
    beschreibung: "Claude-Artefakt: Bau-Dokumentensystem.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "tamara",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\tamar\\Claude\\Artifacts\\baudok-dokumentensystem",
    visibility: "",
    letzterPush: "",
    tags: ["bau", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf Tamara (C:\\Users\\tamar\\Claude\\Artifacts\\baudok-dokumentensystem), nicht auf GitHub. Werkzeug Claude (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "purchase-overview",
    name: "Purchase Overview",
    beschreibung: "Codex-App: Einkaufsübersicht.",
    ursprung: ["Codex"],
    stack: [],
    rechner: "tamara",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\tamar\\Documents\\New project\\purchase-overview-app",
    visibility: "",
    letzterPush: "",
    tags: ["einkauf", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf Tamara (C:\\Users\\tamar\\Documents\\New project\\purchase-overview-app), nicht auf GitHub. Werkzeug Codex (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "system-diagnose",
    name: "System Diagnose",
    beschreibung: "Codex-App: System-Diagnose.",
    ursprung: ["Codex"],
    stack: [],
    rechner: "tamara",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\Users\\tamar\\Documents\\New project\\system-diagnose-app",
    visibility: "",
    letzterPush: "",
    tags: ["tools", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf Tamara (C:\\Users\\tamar\\Documents\\New project\\system-diagnose-app), nicht auf GitHub. Werkzeug Codex (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
  {
    id: "kassenbuch-email",
    name: "Kassenbuch E-Mail",
    beschreibung: "Codex-App: Kassenbuch per E-Mail.",
    ursprung: ["Codex"],
    stack: [],
    rechner: "tamara",
    github: "",
    vercelUrl: "",
    lokalUrl: "",
    lokalPfad: "C:\\2026\\privat\\Codex\\Kassenbuch email",
    visibility: "",
    letzterPush: "",
    tags: ["finanzen", "nur-lokal"],
    status: "aktiv",
    doku: { text: "keine – lokales Projekt ohne GitHub", url: "" },
    analyse: "Lokal auf Tamara (C:\\2026\\privat\\Codex\\Kassenbuch email), nicht auf GitHub. Werkzeug Codex (aus KI-Projekt-Suche). Nach dem Push ziehe ich Technologie, Umfang, Screenshot und Performance nach.",
    performance: null,
    vorschlaege: ["Code zu GitHub hochladen (docs/CODE_HOCHLADEN.md) – danach volle Analyse", "Werkzeug/Beschreibung bei Bedarf per Stift verfeinern"],
    technik: { frontend: "unbekannt – Code noch nicht einsehbar", middleware: "unbekannt", llm: "—", backend: "unbekannt" },
    gestartet: "",
  },
];
