/* HomeLab App-Dashboard – Seed-Registry
   Quelle: GitHub-Repos von Andreas76761 (Stand 2026-07-15) + Platzhalter.
   Alles in der App editierbar; Änderungen liegen im LocalStorage und
   können unter „Daten" als JSON exportiert werden. */

const SEED_VERSION = 1;

const URSPRUENGE = ["Claude", "Codex", "OpenAI", "Perplexity", "Lovable", "Gemini", "Sonstiges"];

const SEED_PCS = [
  { id: "pc1", name: "PC 1", os: "Windows", ort: "", notiz: "" },
  { id: "pc2", name: "PC 2", os: "Windows", ort: "", notiz: "" },
  { id: "pc3", name: "PC 3", os: "Windows", ort: "", notiz: "" },
  { id: "pc4", name: "PC 4", os: "Windows", ort: "", notiz: "" },
];

const SEED_APPS = [
  {
    id: "ai-eventorganizer",
    name: "AI Messe Guide 2026",
    beschreibung: "Verwaltung von AI-Messen, -Konferenzen und -Events (PWA, Supabase optional)",
    ursprung: ["Claude"],
    stack: ["HTML/JS statisch", "PWA", "Supabase"],
    rechner: "pc1",
    github: "https://github.com/Andreas76761/AI_Eventorganizer",
    vercelUrl: "https://ai-messe-guide.vercel.app",
    vercelBestaetigt: true,
    lokalUrl: "http://localhost:8933",
    visibility: "public",
    letzterPush: "2026-07-15",
    tags: ["produktiv", "events"],
    status: "aktiv",
  },
  {
    id: "baudokumentation2026",
    name: "Baudokumentation 2026 V1",
    beschreibung: "",
    ursprung: [],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/baudokumentation2026_V1",
    vercelUrl: "https://baudokumentation2026-v1.vercel.app",
    lokalUrl: "",
    visibility: "public",
    letzterPush: "2026-07-11",
    tags: ["bau"],
    status: "aktiv",
  },
  {
    id: "diagramm-builder",
    name: "Diagramm Builder",
    beschreibung: "",
    ursprung: [],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/Diagramm_Builder",
    vercelUrl: "https://diagramm-builder.vercel.app",
    lokalUrl: "",
    visibility: "private",
    letzterPush: "2026-07-10",
    tags: [],
    status: "aktiv",
  },
  {
    id: "servicevertrag-dashboard",
    name: "ServiceVertrag-Dashboard",
    beschreibung: "",
    ursprung: [],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/ServiceVertrag-Dashboard",
    vercelUrl: "https://servicevertrag-dashboard.vercel.app",
    lokalUrl: "",
    visibility: "private",
    letzterPush: "2026-07-08",
    tags: [],
    status: "aktiv",
  },
  {
    id: "bauplaner",
    name: "Bauplaner Version 1",
    beschreibung: "",
    ursprung: [],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/Bauplaner_Version1",
    vercelUrl: "https://bauplaner-version1.vercel.app",
    lokalUrl: "",
    visibility: "private",
    letzterPush: "2026-06-09",
    tags: ["bau"],
    status: "aktiv",
  },
  {
    id: "paperclip-bau",
    name: "Paperclip Bau",
    beschreibung: "",
    ursprung: [],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/Paperclip_Bau",
    vercelUrl: "https://paperclip-bau.vercel.app",
    lokalUrl: "",
    visibility: "public",
    letzterPush: "2026-06-07",
    tags: ["bau"],
    status: "aktiv",
  },
  {
    id: "thumbnail-generator",
    name: "Thumbnail Generator",
    beschreibung: "",
    ursprung: [],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/Thumnail_Generator",
    vercelUrl: "https://thumnail-generator.vercel.app",
    lokalUrl: "",
    visibility: "public",
    letzterPush: "2026-05-01",
    tags: [],
    status: "aktiv",
  },
  {
    id: "taxflow",
    name: "TaxFlow",
    beschreibung: "",
    ursprung: [],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/TaxFlow",
    vercelUrl: "",
    lokalUrl: "",
    visibility: "private",
    letzterPush: "2026-04-02",
    tags: ["finanzen"],
    status: "aktiv",
  },
  {
    id: "task-hub",
    name: "Task-Hub 2026 V1",
    beschreibung: "",
    ursprung: [],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/Task-Hub-2026-V1",
    vercelUrl: "https://task-hub-2026-v1.vercel.app",
    lokalUrl: "",
    visibility: "public",
    letzterPush: "2026-03-30",
    tags: ["organisation"],
    status: "aktiv",
  },
  {
    id: "ki-hub",
    name: "KI-Hub 2026",
    beschreibung: "",
    ursprung: [],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/KI-Hub-2026",
    vercelUrl: "https://ki-hub-2026.vercel.app",
    lokalUrl: "",
    visibility: "private",
    letzterPush: "2026-03-30",
    tags: ["ki"],
    status: "aktiv",
  },
  {
    id: "simulation-sc",
    name: "Simulation SC V1",
    beschreibung: "",
    ursprung: [],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/Simulation_SC_V1",
    vercelUrl: "https://simulation-sc-v1.vercel.app",
    lokalUrl: "",
    visibility: "public",
    letzterPush: "2026-03-01",
    tags: ["simulation"],
    status: "aktiv",
  },
];
