/* HomeLab App-Dashboard – Seed-Registry
   Quelle: GitHub-Inventur vom 15.07.2026 – alle 11 Repos geklont und analysiert
   (Technologie aus package.json/Code, Umfang gezählt, Ursprung aus README/Commits,
   Screenshots aus lokal gebauten Apps).
   Alles in der App editierbar; Änderungen liegen im LocalStorage und
   können unter „Daten" als JSON exportiert werden. */

const SEED_VERSION = 3;

const URSPRUENGE = ["Claude", "Codex", "OpenAI", "Perplexity", "Lovable", "Gemini", "Sonstiges"];

const SEED_PCS = [
  { id: "pc1", name: "PC 1", os: "Windows", ort: "", notiz: "" },
  { id: "pc2", name: "PC 2", os: "Windows", ort: "", notiz: "" },
  { id: "pc3", name: "PC 3", os: "Windows", ort: "", notiz: "" },
  { id: "pc4", name: "PC 4", os: "Windows", ort: "", notiz: "" },
];

const SEED_APPS = [
  {
    id: "ai-eventorganizer",
    name: "AI Messe Guide 2026",
    beschreibung: "Verwaltung von AI-Messen, -Konferenzen und -Events: Kalender, Programm, Kosten, Reise, Community, PWA (Supabase optional)",
    ursprung: ["Claude"],
    stack: ["HTML/JS statisch", "PWA", "Supabase"],
    rechner: "pc1",
    github: "https://github.com/Andreas76761/AI_Eventorganizer",
    vercelUrl: "https://ai-messe-guide.vercel.app",
    vercelBestaetigt: true,
    lokalUrl: "http://localhost:8933",
    visibility: "public",
    letzterPush: "2026-07-15",
    umfang: { dateien: 31, loc: 4943 },
    screenshot: "screenshots/ai-eventorganizer.png",
    tags: ["produktiv", "events"],
    status: "aktiv",
    bewertung: { nutzen: 0, reifegrad: 4, wartbarkeit: 3, techQualitaet: 4, zukunft: 4,
      notiz: "Vorschlag aus Code-Analyse: sehr funktionsreich und produktiv auf Vercel; app.js als ~5.000-Zeilen-Monolith drückt die Wartbarkeit." },
  },
  {
    id: "diagramm-builder",
    name: "Diagramm Builder",
    beschreibung: "Diagramm-Ersteller mit Dashboard, Sankey, Use Cases und ROI-Berechnung; Import aus CSV/Excel, Export nach Excel/PDF/PowerPoint, 6 Farbschemata",
    ursprung: ["Claude"],
    stack: ["React", "Vite", "Recharts", "xlsx", "jsPDF", "pptxgenjs"],
    rechner: "",
    github: "https://github.com/Andreas76761/Diagramm_Builder",
    vercelUrl: "https://diagramm-builder.vercel.app",
    lokalUrl: "",
    visibility: "private",
    letzterPush: "2026-07-10",
    umfang: { dateien: 61, loc: 7923 },
    screenshot: "screenshots/diagramm-builder.png",
    tags: ["diagramme", "vercel.json vorhanden"],
    status: "aktiv",
    bewertung: { nutzen: 0, reifegrad: 3, wartbarkeit: 4, techQualitaet: 4, zukunft: 4,
      notiz: "Vorschlag aus Code-Analyse: moderner React/Vite-Stack, saubere Komponenten; README noch Vite-Standard." },
  },
  {
    id: "servicevertrag-dashboard",
    name: "ServiceVertrag-Dashboard",
    beschreibung: "Automotive Service Contract Management (v7.5): KPIs, Vertragsvergleich, Garantiepakete, LCC- & ROI-Kalkulator, Aftermarket (Werkstattnetz, Retention, Penetration)",
    ursprung: [],
    stack: ["HTML/JS statisch", "Chart.js (CDN)"],
    rechner: "",
    github: "https://github.com/Andreas76761/ServiceVertrag-Dashboard",
    vercelUrl: "https://servicevertrag-dashboard.vercel.app",
    lokalUrl: "",
    visibility: "private",
    letzterPush: "2026-07-08",
    umfang: { dateien: 27, loc: 17369 },
    screenshot: "screenshots/servicevertrag-dashboard.png",
    tags: ["automotive", "größte App"],
    status: "aktiv",
    bewertung: { nutzen: 0, reifegrad: 4, wartbarkeit: 2, techQualitaet: 3, zukunft: 3,
      notiz: "Vorschlag aus Code-Analyse: inhaltlich sehr umfangreich (v7.5, 17.000+ Zeilen), aber Vanilla-JS ohne Build/Modulsystem und Chart.js vom CDN – Wartung wird mit der Größe schwer." },
  },
  {
    id: "thumbnail-generator",
    name: "Presentation Designer (Thumnail_Generator)",
    beschreibung: "Intelligentes PowerPoint-Archiv: Upload & KI-Analyse, Volltextsuche, Design-Varianten je Folie, Voice-Chat (Claude/GPT-4/Gemini/Llama), OCR, Notion-Sync",
    ursprung: [],
    stack: ["React", "Vite", "Tailwind", "tesseract.js", "Web Worker"],
    rechner: "",
    github: "https://github.com/Andreas76761/Thumnail_Generator",
    vercelUrl: "https://thumnail-generator.vercel.app",
    lokalUrl: "",
    visibility: "public",
    letzterPush: "2026-05-01",
    umfang: { dateien: 55, loc: 6472 },
    screenshot: "screenshots/thumbnail-generator.png",
    tags: ["präsentationen", "multi-llm", "vercel.json vorhanden"],
    status: "aktiv",
    bewertung: { nutzen: 0, reifegrad: 3, wartbarkeit: 3, techQualitaet: 4, zukunft: 4,
      notiz: "Vorschlag aus Code-Analyse: technisch ambitioniert (Web Worker, OCR, virtuelles Scrollen, Multi-LLM); Achtung: Build nutzt GitHub-Pages-Basispfad /Thumnail_Generator/ – ergibt auf Vercel eine weiße Seite." },
  },
  {
    id: "task-hub",
    name: "Task-Hub 2026 V1",
    beschreibung: "Workspace-App aus Google AI Studio: Dashboard, Aktivitäten-Monitor, Dokumentenarchiv, Datei-Upload, Exportbereich, Admin-Bereich",
    ursprung: ["Gemini"],
    stack: ["Angular", "Angular Material", "Firebase", "@google/genai", "D3"],
    rechner: "",
    github: "https://github.com/Andreas76761/Task-Hub-2026-V1",
    vercelUrl: "",
    lokalUrl: "",
    visibility: "public",
    letzterPush: "2026-03-30",
    umfang: { dateien: 59, loc: 10953 },
    screenshot: "screenshots/task-hub.png",
    tags: ["organisation", "ai-studio"],
    status: "aktiv",
    bewertung: { nutzen: 0, reifegrad: 3, wartbarkeit: 3, techQualitaet: 4, zukunft: 4,
      notiz: "Vorschlag aus Code-Analyse: strukturierter Angular-Stack mit Material und Firebase; Firebase-Konfiguration und Gemini-Key nötig, um alles zu nutzen." },
  },
  {
    id: "ki-hub",
    name: "KI-Hub 2026",
    beschreibung: "KI-Portal aus Google AI Studio: Dashboard mit KI-Generierungen, KI-Tools, Dokumente, Aktivitäten, Präsentationen, Administration (benötigt GEMINI_API_KEY)",
    ursprung: ["Gemini"],
    stack: ["React", "Vite", "TypeScript", "@google/genai", "Recharts"],
    rechner: "",
    github: "https://github.com/Andreas76761/KI-Hub-2026",
    vercelUrl: "",
    lokalUrl: "",
    visibility: "private",
    letzterPush: "2026-03-30",
    umfang: { dateien: 24, loc: 1431 },
    screenshot: "screenshots/ki-hub.png",
    tags: ["ki", "ai-studio"],
    status: "aktiv",
    bewertung: { nutzen: 0, reifegrad: 2, wartbarkeit: 3, techQualitaet: 3, zukunft: 3,
      notiz: "Vorschlag aus Code-Analyse: aufgeräumtes React/TypeScript, aber die App stürzt ohne GEMINI_API_KEY komplett ab (weiße Seite) – Key-Handling sollte abgefangen werden." },
  },
  {
    id: "baudokumentation2026",
    name: "Baudokumentation 2026 V1",
    beschreibung: "Baudokumentation, laut README „mit Claude Fable“ (11.07.2026). Auf GitHub liegt bisher nur die README – der Code ist vermutlich lokal.",
    ursprung: ["Claude"],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/baudokumentation2026_V1",
    vercelUrl: "",
    lokalUrl: "",
    visibility: "public",
    letzterPush: "2026-07-11",
    umfang: { dateien: 1, loc: 0 },
    screenshot: "",
    tags: ["bau", "nur-readme"],
    status: "aktiv",
  },
  {
    id: "bauplaner",
    name: "Bauplaner Version 1",
    beschreibung: "„Mockup Bauplaner mit Codex“ (README). Auf GitHub liegt bisher nur die README – der Code ist vermutlich lokal.",
    ursprung: ["Codex"],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/Bauplaner_Version1",
    vercelUrl: "",
    lokalUrl: "",
    visibility: "private",
    letzterPush: "2026-06-09",
    umfang: { dateien: 1, loc: 0 },
    screenshot: "",
    tags: ["bau", "nur-readme"],
    status: "aktiv",
  },
  {
    id: "taxflow",
    name: "TaxFlow",
    beschreibung: "„Built with AI Studio“ (Gemini). Auf GitHub liegt bisher nur die README – App vermutlich in AI Studio bzw. lokal.",
    ursprung: ["Gemini"],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/TaxFlow",
    vercelUrl: "",
    lokalUrl: "",
    visibility: "private",
    letzterPush: "2026-04-02",
    umfang: { dateien: 1, loc: 0 },
    screenshot: "",
    tags: ["finanzen", "ai-studio", "nur-readme"],
    status: "aktiv",
  },
  {
    id: "simulation-sc",
    name: "Simulation SC V1",
    beschreibung: "„Built with AI Studio“ (Gemini). Auf GitHub liegt bisher nur die README – App vermutlich in AI Studio bzw. lokal.",
    ursprung: ["Gemini"],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/Simulation_SC_V1",
    vercelUrl: "",
    lokalUrl: "",
    visibility: "public",
    letzterPush: "2026-03-01",
    umfang: { dateien: 1, loc: 0 },
    screenshot: "",
    tags: ["simulation", "ai-studio", "nur-readme"],
    status: "aktiv",
  },
  {
    id: "paperclip-bau",
    name: "Paperclip Bau",
    beschreibung: "GitHub-Repo ist leer (keine Commits) – App existiert vermutlich nur lokal oder ist noch nicht hochgeladen.",
    ursprung: [],
    stack: [],
    rechner: "",
    github: "https://github.com/Andreas76761/Paperclip_Bau",
    vercelUrl: "",
    lokalUrl: "",
    visibility: "public",
    letzterPush: "2026-06-07",
    umfang: { dateien: 0, loc: 0 },
    screenshot: "",
    tags: ["bau", "repo-leer"],
    status: "pausiert",
  },
];
